### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Attila22000**
Added my part of the project workflow.

### CODE REVIEW

**Review by M3mberTM — CHANGES_REQUESTED** [review]
You didn't write a whole lot. Try writing a bit more as it undervalues how much work you actually did!

**Review by hongqian-li — CHANGES_REQUESTED** [review]
Thanks Attila, but like Richard said, write more detailed information.

**Review by M3mberTM — APPROVED** [review]
Thanks for all your hard work!

**Review by hongqian-li — APPROVED** [review]
All good now, thanks Attila!

**Pull request merged**
